---
output: reprex::reprex_document
knit: reprex::reprex_render
---

Describe your issue very briefly here. Then show it with a minimal, self-contained example in the following R chunk.

```{r}
#install.packages("nflfastR")
library(nflfastR)
library(tidyverse)
library(nflreadr)
```


```{r}

roster <- load_rosters(
  seasons = 1999:2024
)

write.csv(roster, "../data/raw/roster.csv")

```

```{r}

injuries <- load_injuries(
  seasons = 2009:2024
)

write.csv(injuries, "../data/raw/injuries.csv")

```

```{r}

next_gen_passing <- load_nextgen_stats(stat_type = "passing")
next_gen_receiving <- load_nextgen_stats(stat_type = "receiving")
next_gen_rushing <- load_nextgen_stats(stat_type = "rushing")

write.csv(next_gen_passing, '../data/raw/next_gen_passing.csv')
write.csv(next_gen_receiving, '../data/raw/next_gen_receiving.csv')
write.csv(next_gen_rushing, '../data/raw/next_gen_rushing.csv')


```

```{r}
depth <- load_depth_charts(2001:2024)

write.csv(depth, '../data/raw/depth_charts.csv')
```

```{r}
pfr_adv <- load_pfr_advstats(2018:2024)

write.csv(pfr_adv, '../data/raw/pfr_adv.csv')
```

```{r}
trades <- load_trades(seasons = TRUE)

write.csv(trades, '../data/raw/trades.csv')
```

